development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: scicasoft_challenge
  username: scicasoft_chal
  host: mysql.alwaysdata.com
  encoding: utf8
  password: challengepass
  timeout: 5000
